version: '3.4'

services:
  livestreamrecorderbackend:
    image: livestreamrecorderbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 17210:80
    env_file:
      - .env
