services:
  livestreamrecorderbackend:
    image: ghcr.io/recorder-moe/livestreamrecorderbackend
    build:
      context: .
      target: final
      args:
        - BUILD_CONFIGURATION=ApacheCouchDB_Release
      cache_from:
        - ghcr.io/recorder-moe/livestreamrecorderbackend:cache
      cache_to:
        - type=inline
    ports:
      - 80:8080
    env_file:
      - path: .env
        required: false
    environment:
      # This connect to the azure storage emulator
      # https://learn.microsoft.com/zh-tw/azure/storage/common/storage-use-azurite#well-known-storage-account-and-key
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite-emulator:10000/devstoreaccount1;QueueEndpoint=http://azurite-emulator:10001/devstoreaccount1;TableEndpoint=http://azurite-emulator:10002/devstoreaccount1;
      # Issue: Azure Durable Function HttpStart failure: Webhooks are not configured
      # https://stackoverflow.com/a/64404153/8706033
      - WEBSITE_HOSTNAME=localhost:80
      #
      - CORS_SUPPORT_CREDENTIALS=true
      - CORS_ALLOWED_ORIGINS=["https://localhost:4200"]
      - FrontEndUri=https://localhost:4200
      # #
      # - Registration_allowed=false
      # - Seq_ServerUrl=
      # - Seq_ApiKey=
      # #
      # - StorageService=
      # - Blob_ConnectionString=
      # - Blob_ContainerNamePublic=
      # - Blob_ContainerNamePrivate=
      # - S3_Endpoint=
      # - S3_AccessKey=
      # - S3_SecretKey=
      # - S3_Secure=
      # - S3_BucketNamePrivate=
      # - S3_BucketNamePublic=
      # #
      # - CosmosDB_Private_ConnectionString=
      # - CosmosDB_Public_ConnectionString=
      # - CouchDB_Endpoint=
      # - CouchDB_Username=
      # - CouchDB_Password=
      # #
      # - GITHUB_PROVIDER_AUTHENTICATION_ID=
      # - GITHUB_PROVIDER_AUTHENTICATION_SECRET=

  # Azure Storage Emulator, needed for the durable functions
  # You can use your online azure storage account instead and make sure to set the AzureWebJobsStorage env variable to the online connection string
  azurite-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
